package com.indianstudygroup.app_utils

object AppUrlsEndpoint {
    const val USERS_DETAILS = "api/users"
    const val ADD_FCM_TOKEN = "api/addDevice"
    const val PINCODE_DETAILS = "pincode/{pinCode}"
    const val GET_LIBRARY = "api/newlibrary/"
    const val GET_GYM = "api/newgym/"
    const val POST_REVIEW_LIBRARY = "api/library/addreview"
    const val POST_REVIEW_GYM = "api/gym/addreview"
    const val POST_RATING_LIBRARY = "api/library/addrating"
    const val POST_RATING_GYM = "api/gym/addrating"
    const val LIBRARY_BOOK_SEAT = "api/booking/booklibrary"
    const val GYM_BOOK_SEAT = "api/booking/bookgym"
    const val GET_SESSIONS = "api/get-sessions"
    const val GET_GYM_SESSIONS = "api/get-gymsessions"
    const val GET_HISTORY = "api/get-hitory"
    const val GET_GYM_HISTORY = "api/get-gymhistory"
    const val LIBRARY_MARK_ATTENDANCE = "api/mark-attendance"
    const val GYM_MARK_ATTENDANCE = "api/mark-attendance-gym"
    const val GET_INFO = "api/get-info"
    const val WISHLIST_DELETE = "api/librarydetails/modifywishlist"
    const val WISHLIST_DELETE_GYM = "api/librarydetails/modifygymwishlist"
    const val NOTIFICATION_STATUS = "api/changeNotificationStatus"
}